{"name": "Ошибка \"Курьер не найден\" при получении списка заказов", "status": "passed", "description": "Ошибка при получении списка заказов", "start": 1701289415642, "stop": 1701289432274, "uuid": "d16ece5a-d8eb-4de8-99ce-bb0a10eee958", "historyId": "e0e0e28caf4c50843b20f7906cae417f", "testCaseId": "e0e0e28caf4c50843b20f7906cae417f", "fullName": "tests.test_list_order.TestGetOrdersList#test_get_orders_list_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_list_order"}, {"name": "subSuite", "value": "TestGetOrdersList"}, {"name": "host", "value": "DESKTOP-RUURDMU"}, {"name": "thread", "value": "5300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_list_order"}]}